development:
  adapter: redis
  url: redis://localhost:6379/1

test:
  adapter: redis
  url: redis://localhost:6379/2

#production:
#  adapter: redis
#  url: <%#= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
#  channel_prefix: pricehuntertwo_production

production:
  adapter: redis
  url: <%= ENV['REDIS_URL'] %>
  channel_prefix: pricehuntertwo_production
  password: <%= ENV['REDIS_PASSWORD'] %>