default:
  host: localhost
  port: 6379

development:
  db: 0

test:
  db: 1

production:
  db: <%= ENV['REDIS_DB'] %>
  host: <%= ENV['REDIS_URL'] %>
  port: <%= ENV['REDIS_PORT'] %>
  password: <%= ENV['REDIS_PASSWORD'] %>